"""remove email

Revision ID: 2d9a345123d6
Revises: 8d6ed679dbf7
Create Date: 2024-07-03 22:31:24.878376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d9a345123d6"
down_revision: Union[str, None] = "8d6ed679dbf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("users_email_key", "users", ["email"])
    # ### end Alembic commands ###
